[theme]

# Primary accent for interactive elements
primaryColor = '#98FF98'

# Background color for the main content area
backgroundColor = '#F5FFFA'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFFFFF'

# Color used for almost all text
textColor = '#00695C'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"